image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # tzdata wants us to select the geographic area in which we live.
          - apt-get update
          - export DEBIAN_FRONTEND=noninteractive
          - apt-get install -y tzdata
          - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
          - dpkg-reconfigure --frontend noninteractive tzdata
          # Install dependencies
          - echo "deb [trusted=yes] http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list
          - echo "deb [trusted=yes] http://packages.ros.org/ros-testing/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list
          - echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic main" > /etc/apt/sources.list.d/gazebo-stable.list
          - echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-prerelease bionic main" > /etc/apt/sources.list.d/gazebo-prerelease.list
          - apt-get update
          - apt-get -y install build-essential cmake libusb-dev lsb-release mercurial pkg-config python ignition-blueprint python-rosdep
          - rosdep init
          - rosdep update
          - rosdep install --from-paths ./ -i -y --rosdistro melodic
              --skip-keys=ignition-common3
              --skip-keys=ignition-gazebo2
              --skip-keys=ignition-math6
              --skip-keys=ignition-msgs4
              --skip-keys=ignition-plugin1
              --skip-keys=ignition-rendering2
              --skip-keys=ignition-sensors2
              --skip-keys=ignition-transport7
          # SubT
          - mkdir -p /tmp/subt_ws/src
          - ln -s `pwd` /tmp/subt_ws/src
          # Static checker first.
          - cd subt_ign
          - touch /tmp/cpp_check.suppress
          - sh tools/code_check.sh
          - cd /tmp/subt_ws
          # Build and run tests.
          - source /opt/ros/melodic/setup.bash
          - catkin_make
          - catkin_make run_tests -j1
          - catkin_test_results --all --verbose || true
          - catkin_test_results
