image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # tzdata wants us to select the geographic area in which we live.
          - apt-get update
          - export DEBIAN_FRONTEND=noninteractive
          - apt-get install -y tzdata
          - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
          - dpkg-reconfigure --frontend noninteractive tzdata
          # Install dependencies
          - echo "deb [trusted=yes] http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list
          - echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic main" > /etc/apt/sources.list.d/gazebo-stable.list
          - echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-prerelease bionic main" > /etc/apt/sources.list.d/gazebo-prerelease.list
          - apt-get update
          - apt-get -y install mercurial cmake pkg-config cppcheck build-essential lcov curl python git gazebo9 libignition-common-dev libignition-math4-dev libgazebo9-dev ros-melodic-gazebo-dev ros-melodic-gazebo-plugins ros-melodic-gazebo-ros ros-melodic-gazebo-ros-pkgs ros-melodic-xacro
          # Install packages required by subt_ign
          - apt-get -y install libignition-common3-dev libignition-math6-dev libignition-transport6-dev libignition-msgs3-dev libignition-plugin-dev
          # SubT
          - mkdir -p /tmp/subt_ws/src
          - ln -s `pwd` /tmp/subt_ws/src
          # Static checker first.
          - cd subt_gazebo
          - touch /tmp/cpp_check.suppress
          - sh tools/code_check.sh
          - cd /tmp/subt_ws
          # Build and run tests.
          - source /opt/ros/melodic/setup.bash
          - catkin_make
          - catkin_make run_tests -j1
